spring.application.name=backend

spring.config.import=optional:application-secret.properties

spring.datasource.url=${databaseurl}
spring.datasource.username=${databaseusername}
spring.datasource.password=${databasepassword}


jwt.secretKey=${jwtSecretKey}


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${mailUsername}
spring.mail.password=${mailPassword}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.main.allow-circular-references=true